version: '3.3'
services:
  celery:
    build:
      context: .
      dockerfile: backend/celery.Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DB__HOST=postgres
      - DB__PORT=5432
      - DB__USER=dbuser
      - DB__PASSWORD=dbpass
      - DB__NAME=postgres
      - TOKEN=91192678cfea48526ecbfabcc13da31725b647e7aca3dabb
      - BASE_URL=https://interview-fullstack-840922857447.us-central1.run.app
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    depends_on:
      - postgres
      - redis

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB__HOST=postgres
      - DB__PORT=5432
      - DB__USER=dbuser
      - DB__PASSWORD=dbpass
      - DB__NAME=postgres
      - TOKEN=91192678cfea48526ecbfabcc13da31725b647e7aca3dabb
      - BASE_URL=https://interview-fullstack-840922857447.us-central1.run.app
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - TZ=UTC
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    command: postgres -c 'max_connections=10000'

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - app