"""add tables

Revision ID: aabbddec00b1
Revises: 
Create Date: 2024-11-11 03:08:08.565515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabbddec00b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('service_asset_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_asset_id')
    )
    op.create_table('campaign_creative',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'asset_id')
    )
    op.create_table('insight',
    sa.Column('impressions', sa.BIGINT(), nullable=False),
    sa.Column('cpi', sa.REAL(), nullable=False),
    sa.Column('ctr', sa.REAL(), nullable=False),
    sa.Column('cpm', sa.REAL(), nullable=False),
    sa.Column('ipm', sa.REAL(), nullable=False),
    sa.Column('campaign_creative_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_creative_id'], ['campaign_creative.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insight')
    op.drop_table('campaign_creative')
    op.drop_table('asset')
    # ### end Alembic commands ###
